version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:15
    env_file: ./.env
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    container_name: backend
    restart: always
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
        DB_HOST: ${DOCKER_HOST}
        DB_PORT: ${DOCKER_PORT_POSTGRES}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PORT: ${DOCKER_PORT}
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
